
import StyledComponentsRegistry from './lib/registry'
import GlobalStyles from './GlobalStyles'



export const metadata = {
  title: 'SmartStudy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
          
      <body>
      <StyledComponentsRegistry>
      <GlobalStyles/>
        {children}
        </StyledComponentsRegistry>
        </body>
        
    </html>
   
  )
}
